### ISSUE TITLE
Explore Larger Body Type

### ISSUE THREAD

**Issue by jdsimcoe** [RileyTomasek/tight#1]
First, I want to say that I love what you are doing. This plugin is really solid and needed. Here are some quick feedback items:

- Since the interface has been reduced and streamlined for easier reading, I would up the body font size
- In the monospaced font stack, consider adding `"SFMono-Regular"` at the front of the stack for macOS users that have it installed (I've found that SF Mono is really an insanely great and readable monospaced font and it's a shame not to take advantage--GitHub does!)

Keep at it!

**Comment by jdsimcoe** [comment]
@RileyTomasek I'm happy to Fork and PR these things if are you interested in me exploring them.

**Comment by RileyTomasek** [comment]
This was fixed by #2 🎉

**Comment by rileytomasek** [comment]
This was fixed by #2 🎉
