### ISSUE TITLE
How do I create a new chat in Slack?

### ISSUE THREAD

**Issue by alakshmi1030** [RileyTomasek/tight#8]
With tight, I love the readability and overall improved UI. However, I can't seem to find a way to create a new chat with an employee or create a group chat (since the section for new chat seems to be removed). How do I do this?

**Comment by ericorruption** [comment]
Searching for people at the top (magnifier icon) is one way to do it. Not sure about group chats though.

**Comment by rileytomasek** [comment]
You can create chats by using the command+shift+k shortcut. You can also temporarily disable to the extension to do things that need the default UI.
