### ISSUE TITLE
Publish to userstyles.org?

### ISSUE THREAD

**Issue by waynehoover** [RileyTomasek/tight#9]
I already use stylus https://add0n.com/stylus.html to override CSS in websites. Maybe you could publish the css here to userstyles.org so we don't have to have a separate plugin for slack.

**Comment by rileytomasek** [comment]
Sounds good. I'll do it when I get a chance.

**Comment by rileytomasek** [comment]
@waynehoover, I just published Tight to userstyles.org https://userstyles.org/styles/174300/tight-simplified-slack-offered-by-riley-tomasek.

Sorry it took me so long...
